<a href="https://colab.research.google.com/github/ridhimapandey117/Python-Course-YT/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print(arr)

In [ ]:
#In a case like this, np.() will return a 2d array
my_mat = [[1,2,3], [4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,10) #works like range function, including how the "stop" position isn't included

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2) #3rd number is the step size, or the number by which the list skips by

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#If you want to generate a list of certain numbers, do n.[plural number]() (ex. np.twos())
np.ones(3)

array([1., 1., 1.])

In [ ]:
#If you want to make an array of the dimensions you want (add it in as a tuple)
#Format of tuple: (rows, columns)
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,5,10) #like arange, but the third number will provide 10 evenly-spaced points from start to stop position (also it's a 1D array)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4) #np.eye can make a square matrix (which is when rows = cols and there's a diagonal of ones) (bro just run it...)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5) #will randomly generate random numbers

array([0.74077344, 0.69387442, 0.92016466, 0.37518459, 0.4170074 ])

In [ ]:
np.random.rand(5,5) #How to make random.rand 2D array

array([[0.10365233, 0.01862333, 0.86741245, 0.47100681, 0.62182036],
       [0.99399482, 0.02217473, 0.52306352, 0.99850615, 0.32485975],
       [0.99036786, 0.65091361, 0.60854202, 0.84872423, 0.48989342],
       [0.4430875 , 0.64721466, 0.87487334, 0.27419348, 0.27878295],
       [0.22699243, 0.3772297 , 0.34226357, 0.41783634, 0.19348743]])

In [ ]:
np.random.randn(2) #Will generate random numbers from a normal distribution where the mean is 0 (although they won't be integers)

array([ 0.50008118, -0.54728741])

In [ ]:
np.random.randint(3,100,6) #returns random integers from first-->second for third amount of times (not including the second number)

array([71, 13, 68, 41, 66, 57])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([11,  3, 10, 49, 27, 11,  5, 28, 17, 32])

In [ ]:
arr.reshape(5,5) #Reshape an array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max() #finds max value
ranarr.argmax() #returns position of max value

np.int64(3)

In [ ]:
ranarr.min() #finds min value
ranarr.argmin() #returns position of min value

np.int64(1)

In [ ]:
arr.shape #If it prints out (#,), it means it was a 1D vector

(25,)

In [ ]:
arr.dtype #returns data-type

dtype('int64')

In [ ]:
from numpy.random import randint #If you don't want to keep calling .random.whatever everytime. After import, put the method you want to call
randint(2,10) #can call it just like this

4